PayNearMe/PayNearMe/Controllers/ForgotPasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PayNearMe.Models;
using System.Collections;
using System.Configuration;
using MySql.Data.MySqlClient;
using System.Net.Mail;
using System.Net;
using log4net;
using AESEncrypt;
using System.Threading;

namespace PayNearMe.Controllers
{
    public class ForgotPasswordController : Controller
    {
        IDictionary config;
        private String connection = string.Empty;
        private String smtpServer = string.Empty;
        private String smtpUser = string.Empty;
        private String smtpPass = string.Empty;
        private String smtpSender = string.Empty;
        private Boolean smtpSsl = false;
        private ILog kplog;
        private AESEncryption encdata = new AESEncryption();
        private String encStringKey = "B905BD7BFBD902DCB115B327F9018CEA";

        public ForgotPasswordController() {
            config = (IDictionary)(ConfigurationManager.GetSection("PayNearMeAPISection"));
            connection = config["globalcon"].ToString();
            smtpServer = config["smtpServer"].ToString();
            smtpUser = config["smtpUser"].ToString();
            smtpPass = config["smtpPass"].ToString();
            smtpSender = config["smtpSender"].ToString();
            smtpSsl = Convert.ToBoolean(config["smtpSsl"].ToString());
            kplog = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
            
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult CheckEmail(String email)
        {
            ForgotPasswordModelResponse response = new ForgotPasswordModelResponse();
            response.code = 0;
            if (!string.IsNullOrEmpty(email))
            {
                try
                {   using (MySqlConnection con = new MySqlConnection(connection))
                    {   con.Open();
                        using (MySqlCommand cmd = con.CreateCommand())
                        {   cmd.CommandText = "Select UserID, CustomerID, FullName, securityCode from kpcustomersglobal.PayNearMe where UserID = @email";
                            cmd.Parameters.AddWithValue("email", email);

                            MySqlDataReader rdr = cmd.ExecuteReader();
                            if (rdr.HasRows)
                            {   response.code = 1;
                                response.message = "Verified!..";

                                rdr.Read();
                                    response.encCID = encdata.AESEncrypt(rdr["CustomerID"].ToString(), encStringKey);
                                    response.encFN = encdata.AESEncrypt(rdr["FullName"].ToString(), encStringKey);
                                    response.isForgot = rdr["securityCode"].ToString() != string.Empty ? true : false; ;
                                rdr.Close();
                            }
                            else
                                response.message = "The email address specified <br /> has not been registered.";
                        }
                    }
                }
                catch (Exception ex)
                {   response.code = -1;
                    response.message = "A System Error has occured Please try again.";
                    kplog.Error("[CheckEmail] System Error: " + ex.Message);
                }
            }
            else
                response.message = "Please kindly provide an <br /> email address.";

            return new JsonResult { Data = response };
        }

        [HttpPost]
        public JsonResult RequestCode(String email, String encCID, String encFN)
        {   
            ForgotPasswordModelResponse response = new ForgotPasswordModelResponse();

            if (!string.IsNullOrEmpty(email) &&
                !string.IsNullOrEmpty(encFN) &&
                !string.IsNullOrEmpty(encCID) )
            {
                String custID = encdata.AESDecrypt(encCID.Replace(' ', '+'), encStringKey);
                String fullName = encdata.AESDecrypt(encFN.Replace(' ', '+'), encStringKey);

                Random random = new Random();
                const string chars = "9AB8CD7EF6GH5IJ4KL3MN2OP1QR0ST9UV8WX7YZ6012345";
                String securityCode = new string(Enumerable.Repeat(chars, 4).Select(s => s[random.Next(s.Length)]).ToArray());

                try
                {   using (MySqlConnection con = new MySqlConnection(connection))
                    {   con.Open();
                        using (MySqlCommand cmd = con.CreateCommand())
                        {   cmd.CommandText = "UPDATE `kpcustomersglobal`.`PayNearMe` SET securityCode = @securityCode WHERE CustomerID = @custID AND FullName = @fullName";
                            cmd.Parameters.AddWithValue("securityCode", securityCode);
                            cmd.Parameters.AddWithValue("custID", custID);
                            cmd.Parameters.AddWithValue("fullName", fullName);
                            if (cmd.ExecuteNonQuery() > 0)
                            {   if (sendSecurityCode(email, securityCode, custID, fullName))
                                {   response.code = 1;
                                    response.message = "Code sent,<br /> Please check your email.";
                                }
                                else
                                {   response.code = 0;
                                    response.message = "Service error : Unable to mail code, <br /> send request timeout.";
                                }
                            }
                            else
                                throw new Exception("Server Error : failed to update security code.");
                        }
                    }
                }
                catch (Exception ex)
                {   kplog.Error("[RequestCode] where email = '" + email + "', encCID = '" + encCID + "', encFN = '" + encFN + "'; ErrorMessage = " + ex.ToString());
                    response.code = -1;
                    response.message = "Server error upon generating security code.";
                }
            }
            else
            {   response.code = 0;
                response.message = "Invalid request code data.";
            }
            return new JsonResult { Data = response };
        }

        [HttpPost]
        public JsonResult ResendCode(String email, String encCID, String encFN)
        {
            ForgotPasswordModelResponse response = new ForgotPasswordModelResponse();
            response.code = 0;

            if (!string.IsNullOrEmpty(email) &&
                !string.IsNullOrEmpty(encFN) &&
                !string.IsNullOrEmpty(encCID))
            {
                String custID = encdata.AESDecrypt(encCID.Replace(' ', '+'), encStringKey);
                String fullName = encdata.AESDecrypt(encFN.Replace(' ', '+'), encStringKey);

                try
                {   using (MySqlConnection con = new MySqlConnection(connection))
                    {   con.Open();
                        using (MySqlCommand cmd = con.CreateCommand())
                        {
                            cmd.CommandText = "SELECT securityCode FROM `kpcustomersglobal`.`PayNearMe` WHERE UserID = @email AND CustomerID = @custID AND FullName = @fullName";
                            cmd.Parameters.AddWithValue("email", email);
                            cmd.Parameters.AddWithValue("custID", custID);
                            cmd.Parameters.AddWithValue("fullName", fullName);

                            MySqlDataReader rdr = cmd.ExecuteReader();
                            if (rdr.HasRows)
                            {   rdr.Read();
                                String securityCode = rdr["securityCode"].ToString();
                                rdr.Close();

                                if (securityCode != string.Empty)
                                {
                                    if (sendSecurityCode(email, securityCode, custID, fullName))
                                    {   response.code = 1;
                                        response.message = "Code sent,<br /> Please check your email.";
                                    }
                                    else
                                        response.message = "Service error : Unable to mail code, <br /> send request timeout.";
                                }
                                else
                                    response.message = "Data provided an error, <br /> Please refresh the page."; 
                            }
                            else
                                response.message = "Unable to find user info, <br /> Please refresh the page."; 
                        }
                    }
                }
                catch (Exception ex)
                {
                    kplog.Error("[ResendCode] where email = '" + email + "', encCID = '" + encCID + "', encFN = '" + encFN + "'; ErrorMessage = " + ex.ToString());
                    response.code = -1;
                    response.message = "Server error upon resending security code.";
                }
            }
            return new JsonResult { Data = response };
        }

        private string generateAutoForgotPasswordLink(String email, String securityCode, String custID, String fullName)
        {
            string baseUrl = Request.Url.Scheme + "://" + Request.Url.Authority + Request.ApplicationPath.TrimEnd('/') + "/";
            string controllerLink = "ForgotPassword/fpConfReq?";
            string encData = "e=" + encdata.AESEncrypt(email.ToString(), encStringKey).Replace(' ', '+') + '&'
                           + "sc=" + encdata.AESEncrypt(securityCode.ToString(), encStringKey).Replace(' ', '+') + '&'

PayNearMe/PayNearMe/Views/ForgotPassword/Index.cshtml
@model PayNearMe.Models.ForgotPasswordModel
@{ ViewBag.Title = "Forgot Password"; }

<div class="fpHeader">
    <h2 class="col-md-12" style="color: white;"><b>Forgot Password</b></h2>
</div>
<div class="fpBody col-md-12">
    <h2>Let's retrieve your account!</h2>
    Please fill in all the fields shown.
    
    @using (Html.BeginForm("fpChangePassword", "ForgotPassword", FormMethod.Post, new { id = "ForgotPassword-Form", enctype = "multipart/form-data", @class = "fpDataContainer" }))
    {
        @Html.AntiForgeryToken()
        <div id="emailView" class="clearfix form-group fpDataHolder fpShow">
            <div id="emailInnerView" class="fpInner fpInnerShow">
                <div class="col-sm-5" style="padding-top: 15px;">
                    What is your e-mail address ?
                </div>
                <div class="col-sm-7">
                    @Html.TextBoxFor(model => model.email, new { @style = "width: 100%; text-align: center; text-transform: lowercase;", @placeholder = "e-mail address" })
                    @Html.ValidationMessageFor(model => model.email)
                </div>
                <div class="col-sm-7 col-sm-offset-5 text-right">
                    <button id="btnSendConfirmationCode" class="fpBtn" title="Request For A Code"
                            type="button" onclick="checkEmail($('#email'))">
                        Verify E-mail Address
                    </button>
                </div>
            </div>
        </div>
        <div id="codeView" class="clearfix form-group fpDataHolder fpHide">
            <div id="codeInnerView" class="fpInner fpInnerHide">
                <div class="col-sm-8" style="padding-top: 15px;">
                    Please input confimation code sent to you via email
                </div>
                <div class="col-sm-4">
                    @Html.TextBoxFor(model => model.securityCode, new { @style = "width: 100%; text-align: center; text-transform: uppercase;", @placeholder = "security code", @maxlength = 4 })
                </div>
                <div class="col-sm-7 col-sm-offset-5 text-right">
                    <div style="border-right: 1px solid black; padding-right: 10px; padding-bottom: 5px; margin-right: 5px; display: inline-block;">
                        <a title="Didn't receive any email? Click to resend"
                           onclick="checkEmail($('#email'))" style="cursor: pointer;">
                            Resend Code
                        </a>
                    </div>
                    <button type="button" class="fpBtn" title="Apply request" onclick="checkCode($('#email'), $('#securityCode'))" style="text-align: justify;">Verify Code</button>
                </div>
            </div>
        </div>
        <div id="newpassView" class="clearfix form-group fpDataHolder fpHide">
            <div id="newpassInnerView" class="fpInner fpInnerHide">
                <div class="col-sm-5" style="padding-top: 15px;">
                    New Password :
                </div>
                <div class="col-sm-7">
                    @Html.TextBoxFor(model => model.fpNewPassword, new { @style = "font-size: 30px; width: 100%; text-align: center;", @placeholder = "new password", @type = "password" })
                    <span class="msgPassError glyphicon" style="position: absolute; right: 15px; padding: 15px;"></span>
                    <div id="msgfpNewPassword" class="msgPassError hidden"
                         style="width: 100%; text-align: center; font-size: 14px; color: #ff000a; padding: 5px;">
                    </div>
                </div>
                <div class="col-sm-5" style="padding-top: 15px;">
                    Confirm New Password :
                </div>
                <div class="col-sm-7">
                    @Html.TextBoxFor(model => model.fpConfirmPassword, new { @style = "font-size: 30px; width: 100%; text-align: center;", @placeholder = "confirm new password", @type = "password" })
                    <span class="msgConfPassError glyphicon" style="position: absolute; right: 15px; padding: 15px;"></span>
                    <div id="msgfpConfirmPassword" class="msgConfPassError hidden"
                         style="width: 100%; text-align: center; font-size: 14px; color: #ff000a; padding: 5px;">
                    </div>
                </div>
                <div class="col-sm-7 col-sm-offset-5 text-right">
                    <button type="submit" class="fpBtn" title="Confirm New Password">Change Password</button>
                </div>
            </div>
        </div>
    }
    <div style="display: table; text-align: right; padding: 30px 0; background-color: #eee; width: 100%; padding: 15px; border-bottom-left-radius: 5px; border-bottom-right-radius: 5px;">
        @Html.ActionLink("Go back to Login Page", "Login", "Account").
    </div>
</div>



<div id="fpMsgModal" class="hidden" style="position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); width: 300px; z-index: 2001;">
    <div class="col-md-12" style="background: red; font-size: 18px; color: white; border-top-left-radius: 8px; border-top-right-radius: 8px; padding: 5px; border: 1px solid red;">
        Message
    </div>
    <div class="col-md-12" style="background: white; border-bottom: 2px solid red; border-right: 1px solid red; border-left: 1px solid red; padding: 10px; border-bottom-left-radius: 8px; border-bottom-right-radius: 8px;">
        <div id="msgContainer" class="col-md-12" style="text-align: center; margin: 5px;">Please Wait...</div>
        <br />
        <center>
            <button id="fpmsgbtn" data-login ="@Url.Action("Login", "Account")" onclick="hideModals()" class="fpBtn">- OK -</button>
        </center>
    </div>
</div>

PayNearMe/PayNearMe/Views/ForgotPassword/fpConfReq.cshtml
@model PayNearMe.Models.ForgotPasswordModel
@{ ViewBag.Title = "Forgot Password"; }

<div class="fpHeader">
    <h2 class="col-md-12" style="color: white;"><b>Forgot Password</b></h2>
</div>
<div class="fpBody col-md-12">
    <h2>Let's retrieve your account!</h2>
    <div>
        Please fill in all the fields shown.

        @using (Html.BeginForm("fpChangePassword", "ForgotPassword", FormMethod.Post, new { id = "ForgotPassword-Form", enctype = "multipart/form-data", @class = "fpDataContainer", style = "min-height: auto;" }))
        {
            @Html.AntiForgeryToken()
            @Html.TextBoxFor(model => model.email, new { @style = "display: none;" })
            @Html.TextBoxFor(model => model.securityCode, new { @style = "display: none;" })

            <div id="newpassView" class="clearfix form-group">
                <div id="newpassInnerView" class="fpInner">
                    <div class="col-sm-5" style="padding-top: 15px;">
                        New Password :
                    </div>
                    <div class="col-sm-7">
                        @Html.TextBoxFor(model => model.fpNewPassword, new { id = "fpNewPassword", @style = "font-size: 30px; width: 100%; text-align: center;", @placeholder = "new password", @type = "password" })
                        <span class="msgPassError glyphicon" style="position: absolute; right: 15px; padding: 15px;"></span>
                        <div id="msgfpNewPassword" class="msgPassError hidden"
                             style="width: 100%; text-align: center; font-size: 14px; color: #ff000a; padding: 5px;">
                        </div>
                    </div>
                    <div class="col-sm-5" style="padding-top: 15px;">
                        Confirm New Password :
                    </div>
                    <div class="col-sm-7">
                        @Html.TextBoxFor(model => model.fpConfirmPassword, new { id = "fpConfirmPassword", @style = "font-size: 30px; width: 100%; text-align: center;", @placeholder = "confirm new password", @type = "password" })
                        <span class="msgConfPassError glyphicon" style="position: absolute; right: 15px; padding: 15px;"></span>
                        <div id="msgfpConfirmPassword" class="msgConfPassError hidden"
                             style="width: 100%; text-align: center; font-size: 14px; color: #ff000a; padding: 5px;">
                        </div>
                    </div>
                    <div class="col-sm-7 col-sm-offset-5 text-right">
                        <button type="submit" class="fpBtn" title="Confirm New Password">Change Password</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<div id="fpMsgModal" class="hidden" style="position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); width: 300px; z-index: 2001;">
    <div class="col-md-12" style="background: red; font-size: 18px; color: white; border-top-left-radius: 8px; border-top-right-radius: 8px; padding: 5px; border: 1px solid red;">
        Message
    </div>
    <div class="col-md-12" style="background: white; border-bottom: 2px solid red; border-right: 1px solid red; border-left: 1px solid red; padding: 10px; border-bottom-left-radius: 8px; border-bottom-right-radius: 8px;">
        <div id="msgContainer" class="col-md-12" style="text-align: center; margin: 5px;">Please Wait...</div>
        <br />
        <center>
            <button id="fpmsgbtn" data-login="@Url.Action("Login", "Account")" onclick="hideModals()" class="fpBtn">- OK -</button>
        </center>
    </div>
</div>

<script>
    $(document).ready(function () {

        var fpPassIndicator = false,
            fpConfirmPass = false,
            fpNewPassword = false;
        $('input#fpNewPassword').focusout(function (e) {
            var currInput = $(this).val(),
                upperLetter = false,
                smallLetter = false,
                hasNumber = false;
            fpPassIndicator = false;
            fpConfirmPass = false;
            fpNewPassword = false;

            if (currInput == "")
                inputInvalid('fpNewPassword', 'msgPassError', 'Password field is required');
            else if (currInput.length < 8)
                inputInvalid('fpNewPassword', 'msgPassError', 'Password should be atleast 8 characters long');
            else {
                for (var count = 0; (count < currInput.length && (!smallLetter || !hasNumber || !upperLetter)) ; count++) {
                    if (!isNaN(currInput[count]))
                    { hasNumber = true; }
                    else if (currInput[count] == currInput[count].toUpperCase())
                    { smallLetter = true; }
                    else if (currInput[count] == currInput[count].toLowerCase())
                    { upperLetter = true; }
                }

                if (smallLetter && hasNumber && upperLetter) {
                    inputValid('fpNewPassword', 'msgPassError');
                    fpPassIndicator = true;
                    fpNewPassword = true;
                }
                else {
                    fpPassIndicator = false;
                    fpNewPassword = false;
                    inputInvalid('fpNewPassword', 'msgPassError', 'Password must contain atleast 1 lowercase letter, 1 uppercase letter & 1 digit number');
                }
            }

            if (fpPassIndicator) {
                if ($('input#fpConfirmPassword').val() != $('input#fpNewPassword').val()) {
                    inputInvalid('fpConfirmPassword', 'msgConfPassError', 'Password mismatch');
                }
                else {
                    inputValid('fpConfirmPassword', 'msgConfPassError');
                }
            }
            else {
                $('.msgConfPassError').addClass('hidden');
            }
        });

        $('input#fpConfirmPassword').keyup(function (e) {
            if (fpPassIndicator) {
                if (($(this).val() != $('input#fpNewPassword').val()) || $(this).val() == "" || $('input#fpNewPassword').val() == "") {
                    fpConfirmPass = false;
                    inputInvalid('fpConfirmPassword', 'msgConfPassError', 'Password mismatch');
                }
                else {
                    fpConfirmPass = true;
                    inputValid('fpConfirmPassword', 'msgConfPassError');
                    $('span.msgPassError').removeClass('glyphicon-remove');
                    $('span.msgPassError').removeClass('glyphicon-ok');
                }
            }
        });

        //$('form#ForgotPassword-Form').submit(function (e) {
        //    e.preventDefault();

        //    if (fpPassIndicator && fpConfirmPass && fpNewPassword) {
        //        ajxloadtoggle("Confirming new password...");
        //        $.ajax({
        //            url: '../ForgotPassword/fpChangePassword',
        //            type: "POST",
        //            data: $('form#ForgotPassword-Form').serialize(),
        //            success: function (data) {
        //                if (data.code == 0)
        //                    fpMsgBox(data.message);
        //                else if (data.code == 1) {
        //                    fpMsgBox(data.message);
        //                    setTimeout(function () {
        //                        var uri = $("#fpmsgbtn").attr("data-login");
        //                        window.location.href = uri;
        //                    }, 3000);
        //                }
        //                else {
        //                    alert(data.message);
        //                    ajxloadtoggle();
        //                }
        //            },
        //            error: function (error) {
        //                alert("Something went wrong, Please try again!");
        //                ajxloadtoggle();
        //            }
        //        });
        //    }
        //});
    });

    var globalEncCID = "", globalEncFN = "";

    function fpMsgBox(msg) {
        $('#fpMsgModal').removeClass('hidden');
        document.getElementById('msgContainer').innerHTML = msg;
    }

    function hideModals() {
        ajxloadtoggle('Loading...');
        ajxloadtoggle();
        $('#fpMsgModal').addClass('hidden')
    }
</script>