PayNearMe/PayNearMe/Controllers/SendController.cs
using log4net;
using MySql.Data.MySqlClient;
using Newtonsoft.Json;
using PayNearMe.Controllers.api;
using PayNearMe.Models;
using PayNearMe.Models.Response;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using ZXing;
using ZXing.Common;

namespace PayNearMe.Controllers
{
   
    public class SendController : Controller
    {
        //
        // GET: /Send/
        WebServiceController service;
        private String connection = string.Empty;
        IDictionary config;
        private ILog kplog;
        //private static double pnmCharge = 3.99;
        private String siteIdentifier = string.Empty;
        private static string wsuser = "wsuser";
        private static string wspass = "wspasswordRrykuqt14!";
        private double pnmCharge = 3.99;
        private double pnmCharge501 = 5.99;
       
        public SendController() 
        {
            config = (IDictionary)(ConfigurationManager.GetSection("PayNearMeAPISection"));
            connection = config["globalcon"].ToString();
            siteIdentifier = config["siteIdentifier"].ToString();
            pnmCharge = Convert.ToDouble(config["pnm500Charge"]);
            pnmCharge501 = Convert.ToDouble(config["pnmAbove500Charge"]);
            
            service = new WebServiceController();
          
            kplog = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }


        public ActionResult Send()
        {

            if (Session["UserID"] == null)
            {
                return RedirectToAction("Login", "Account");
            }

            SendModel model = new SendModel();

            if (TempData["ErrorMessage"] != null) 
            {
                model.Error = TempData["ErrorMessage"].ToString();
            }

          
         
            
            CustomerResultResponse res = new CustomerResultResponse();
            res = service.getbeneficiarylist(Session["CustomerID"].ToString());

            List<SelectListItem> listselect = new List<SelectListItem>();

            listselect.Add(new SelectListItem 
            {
                Value = "",
                Text = "--Select--"
            });

            if (res.benelist != null)
            {

                for (int x = 0; x < res.benelist.Count; x++)
                {
                    listselect.Add(new SelectListItem
                    {
                        Value = res.benelist[x].receiverCustID,
                        Text = res.benelist[x].firstName + " " + res.benelist[x].lastname

                    });
                }

            }

            var rFrex = service.GetBranchRates("711", "3", "USD");
            if (rFrex.rescode == "1")
            {

                model.trans.ExchangeRate = Convert.ToDouble(rFrex.buying);
                Session["ExchangeRate"] = model.trans.ExchangeRate;

            }
            else
            {
                Session["ErrorMessage"] = "Something Went Wrong, Please Try Again!";
                return RedirectToAction("Login", "Account");
            }


            model.beneficiarylist = listselect;
            TempData["ErrorMessage"] = null;
            model.siteIdentifier = siteIdentifier;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Submit(SendModel model,Double NetTransferFee, Double TotalAfterDiscount)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    String errorALL = string.Empty;
                    foreach (ModelState modelState in ViewData.ModelState.Values)
                    {
                        foreach (ModelError error in modelState.Errors)
                        {
                             errorALL = errorALL + Environment.NewLine + error.ErrorMessage;
                        }
                    }

                    return Json(new { respcode = "failed", message = errorALL }, JsonRequestBehavior.AllowGet);
                }


                if (!string.IsNullOrEmpty(model.trans.PromoCode))
                {
                    model.trans.Charge = NetTransferFee;
                    model.trans.Total = TotalAfterDiscount;
                  
                }
               
              
                var trans = new TransactionModel()
                {
                    TransactionType = "Web",
                   // KPTN = ws.generateKPTNGlobal("711",3),
                    Principal = model.trans.Principal,
                    Charge = model.trans.Charge,
                    ExchangeRate = model.trans.ExchangeRate,
                    POAmountPHP = model.trans.POAmountPHP,
                    Total = model.trans.Total,
                    receiverCustId = model.receiver,
                    senderCustID = Session["CustomerID"].ToString(),
                    PromoCode = string.IsNullOrEmpty(model.trans.PromoCode) ? "" : model.trans.PromoCode,
                    Discount = model.trans.Discount
                    

                };

                var response = service.createOrder(trans);
                if (response.status == "ok")
                {
                    return Json(new { respcode = response.status, trackingUrl = response.order.order_tracking_url, amount = response.order.order_amount }, JsonRequestBehavior.AllowGet);
                }
                else 
                {
                    return Json(new { respcode = "failed", message = response.errors[0].description }, JsonRequestBehavior.AllowGet);
                }
    
              
           
            }
            catch (Exception ex)
            {
                return Json(new { respcode = "failed", message = ex.ToString() }, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpGet]
        public ActionResult getCharge(Double amount, String bcode, String zcode)
        {


            Double dailyLimit = service.getDailyLimit(Session["CustomerID"].ToString());
            Double monthlyLimit = service.getMonthlyLimit(Session["CustomerID"].ToString());

            if (amount > dailyLimit)
            {
                return Json(new ChargeResponse { respcode = 0, message = "Daily Limit Exceeded", charge = 0 }, JsonRequestBehavior.AllowGet);
            }
            else if (amount > monthlyLimit)
            {
                return Json(new ChargeResponse { respcode = 0, message = "Monthly Limit Exceeded", charge = 0 }, JsonRequestBehavior.AllowGet);
            }

            var chargeGResp = calculateChargePerBranchGlobal(amount, bcode, zcode);
            if (chargeGResp.respcode == 1)
            {
                Decimal partialCharge;
                Decimal partialTotal = Convert.ToDecimal(amount) + chargeGResp.charge + Convert.ToDecimal(pnmCharge);
                if (partialTotal > 500)
                {
                     partialCharge = chargeGResp.charge + Convert.ToDecimal(pnmCharge501);
                }
                else 
                {
                     partialCharge = chargeGResp.charge + Convert.ToDecimal(pnmCharge);
                }
                chargeGResp.charge = partialCharge;

                return Json(chargeGResp, JsonRequestBehavior.AllowGet);

            }
            else if (chargeGResp.respcode == 16)
            {
                var response = calculateChargeGlobal(amount, bcode, zcode);
                if (response.charge == 0)
                {
                    return Json(new ChargeResponse { respcode = 1, message = "Success", charge = 0 }, JsonRequestBehavior.AllowGet);

                }
                else
                {
                    Decimal partialCharge;
                    Decimal partialTotal = Convert.ToDecimal(amount) + response.charge + Convert.ToDecimal(pnmCharge);
                    if (partialTotal > 500)
                    {
                        partialCharge = response.charge + Convert.ToDecimal(pnmCharge501);
                    }
                    else
                    {
                        partialCharge = response.charge + Convert.ToDecimal(pnmCharge);
                    }
                    response.charge = partialCharge;

                 //   response.charge = response.charge + Convert.ToDecimal(pnmCharge);
                    return Json(response,JsonRequestBehavior.AllowGet);
                }

            }
            else
            {

                return Json(chargeGResp, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult validatePromoCode(String Username, String Password,String promoCode, Double Charge, Double Amount) 
        {

            try
            {

            

            PromoResponse resp = new PromoResponse();

            if (Username != wsuser || Password != wspass) 
            {
                resp = new PromoResponse { respcode = 0, message = "UnAuthorizeAccess"};
                return new JsonResult { Data = JsonConvert.SerializeObject(resp), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
            String customerID = Session["CustomerID"].ToString();
            DateTime dt = service.getServerDateGlobal(false);

            using (MySqlConnection con = new MySqlConnection(connection)) 
            {
                con.Open();

                using (MySqlCommand cmd = con.CreateCommand()) 
                {
                    cmd.CommandText = "Select * FROM kpformsglobal.PayNearMePromoCode where promoCode = @promoCode AND (@dt BETWEEN dateFrom and dateTo)";
                    cmd.Parameters.AddWithValue("promoCode", promoCode );
                    cmd.Parameters.AddWithValue("dt", dt.ToString("yyyy-MM-dd HH:mm:ss"));

PayNearMe/PayNearMe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title style="font-weight: bold;">@ViewBag.Title - MLhuillier Online Remittance</title>
    <link rel="shortcut icon" href="@Url.Content("~/Images/favicon.ico")" />
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Styles.Render("~/Styles/cssBundle")
    <script>
        //function ajxloadtoggle() {
        //    if ($("#ml-ajx-load").hasClass("ajxloadhide")) {
        //        $("#ml-ajx-load").removeClass("ajxloadhide");
        //        $("#ml-ajx-load").addClass("ajxloadshow");
        //    }
        //    else {
        //        $("#ml-ajx-load").removeClass("ajxloadshow");
        //        $("#ml-ajx-load").addClass("ajxloadhide");
        //    }
        //}

        function ajxloadtoggle(msg) {
            if (typeof msg != "string")
            {
                if ($("#ml-ajx-load").hasClass("ajxloadhide")) {
                    $("#ml-ajx-load").removeClass("ajxloadhide");
                    $("#ml-ajx-load").addClass("ajxloadshow");
                }
                else {
                    $("#ml-ajx-load").removeClass("ajxloadshow");
                    $("#ml-ajx-load").addClass("ajxloadhide");
                }
            }
            else {
                document.getElementById("ajxMsg").innerHTML = typeof msg == "" ? "Please Wait..." : msg;
                if ($("#ml-ajx-load").hasClass("ajxloadhide")) {
                    $("#ml-ajx-load").removeClass("ajxloadhide");
                    $("#ml-ajx-load").addClass("ajxloadshow");
                }
            }
        }
    </script>
</head>
<body onload="noBack()" onpageshow="if (event.persisted) noBack();">
   
    <header class="navbar navbar-default  navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <img src="~/Images/mlhuillierbanner.png" style="margin-bottom: 10px;padding-top: 10px;">
            </div>
            @if (ViewBag.Title != "Log In" && ViewBag.Title != "Sign Up" && ViewBag.Title != "Authenticate" && ViewBag.Title != "Forgot Password")
            { 
                <div id="navbar-login">
                    <div class="navbar-collapse collapse" style="height: 1px;">
                        <ul class="nav navbar-nav">
                            @if (ViewBag.Title != "Home") { 
                                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            }
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false">Send Money <i class="fa fa-chevron-down"></i></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Send Money", "Send", "Send")</li>
                                    <li>@Html.ActionLink("Transaction History", "Transaction", "TransactionHistory")</li>
                                    <li>@Html.ActionLink("Beneficiaries", "Benefeciaries","Benefeciary")</li>
                                       

                                </ul>

                            </li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false" aria-expanded="false">My Account <i class="fa fa-chevron-down"></i></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Edit Profile", "Index", "Profile")</li>
                                    <li>@Html.ActionLink("Change Password", "ChangePassword", "Profile")</li>
                                    <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                                </ul>

                            </li>
                        </ul>
                    </div>
                </div>
            }
        </div>
    </header>
    
    <div class="container">
        <div class="modal" id="modal-inactivity" data-backdrop="static" data-keyboard="false">
            <div class="modal-content" style="text-align:center;width:50%">
                <div class="panel-heading panel-modal-heading">
                    MESSAGE
                </div>
                <div class="panel-body panel-modal-body">
                    
                    <p>Your current session has expired. For your security, please Login again.</p>
                    
                    @Html.ActionLink("Okay", "sessionExpire", "Account", null, new { @class = "btn btn-success" })
                </div>
            </div>
        </div>

        <div id="myModal" class="modal">
            @*<div class="modal-header"></div>*@
            <div class="modal-content">
                <div class="panel-heading panel-modal-heading">
                    MESSAGE:
                    <span style="font-size:inherit" class="close" id="closeModal">&times;</span>
                </div>
                <div class="panel-body panel-modal-body">
                    <p id="modContent"></p>
                </div>
            </div>
            @*<div class="modal-footer"></div>*@
        </div>

        @if (Session["ErrorMessage"] != null)
        {
            <div id="myModalErrorHandle" class="modal" style="display:block">
            @*<div class="modal-header"></div>*@
            <div class="modal-content">
                <div class="panel-heading panel-modal-heading">
                    MESSAGE: 
                    <span style="font-size:inherit" class="close" id="closeModalmessage">&times;</span>
                </div>
                <div class="panel-body panel-modal-body">
                    <p >@Session["ErrorMessage"].ToString()</p>
                </div>
            </div>
                   @{
            if (Convert.ToBoolean(Session["fromLogin"]))
            {
                Session.Clear();
            }
            else
            {
                Session["ErrorMessage"] = null;
            }
                    
                   
                    }
  
    

            @*<div class="modal-footer"></div>*@

            </div>
        }
        <div id="contentBody" style="min-width: 500px;">
            @RenderBody()
        </div>
  
        <div class="col-md-12" style="margin: 10px 0px;; position: relative;">
            <div style="background-color: rgba(255,0,10,0.9); display: inline-block; border-left: 5px solid rgba(255,0,10,0.9); border-right: 5px solid rgba(255,0,10,0.9); border-bottom: 5px solid rgba(255,0,10,0.9); height: 50px; border-radius: 30px; position: absolute;">
                <img src="~/Images/icon-phone.png" style="height: 100%;">
            </div>
            <div style="display: inline-block; margin-left: 60px; padding: 6px; font-weight: 700;">
                Toll Free: (844) 456-2543 <br />
                Email: support@mlhuillierusa.com
            </div>
        </div>
    </div>

    <footer class="footer-r">
        <div class="inner">
            <p class="">&copy; @DateTime.Now.Year ─ <b>M. Lhuillier</b> Financial Services Inc. All rights reserved</p>
        </div>
    </footer>

    <div id="ml-ajx-load" class="ajxloadhide"
         style="position: fixed; width: 100%; height: 100%; background-color: rgba(0,0,0,0.5); top: 0px; color: white; font-weight: normal; font-size: 12px; transition-duration: 0.5s;">
        <div style="position: absolute; top: 48%; left: 50%; width: 100px; height: 90px; margin: -42px 0 0 -50px;">
            <img id="MLLogo-Ajax-Circle" src="~/Images/_CircleAjaxLoad.svg" style="user-select: none" />
            <img id="MLLogo-Diamond" src="~/Images/_MLAjaxLoad.svg" style="user-select: none" />
            <div id="ajxMsg" 
                 style="text-align: center; user-select: none; position: absolute; bottom: 0px; left: 50%; transform: translateX(-50%); width: 200px; height: 35px;">
                Please Wait...
            </div>
        </div>
    </div>
    @if (ViewBag.Title == "Sign Up")
    {
        @Html.Partial("_Agreement")
    }

</body>
@RenderSection("scripts", required: false)
@RenderSection("styes", required: false)
</html>

@if (ViewBag.Title != "Log In" && ViewBag.Title != "Sign Up" && ViewBag.Title != "Forgot Password" && ViewBag.Title != "Error")
{
<script>
// 5mins popup
    $(document).ready(function () {
             idleTime = 0;
            $(document).ready(function () {
                $limit = 300;

                function timerIncrement() {
                    idleTime = idleTime + 1;
                    if (idleTime > $limit) { // 10 seconds
                        $('#modal-inactivity').modal("show");
                        idleTime = 0;
                    }
                }
                // Increment the idle time counter every second.
                var idleInterval = setInterval(timerIncrement, 1000); // 1 second

                // Zero the idle timer on mouse movement.
                $(this).mousemove(function (e) {
                    idleTime = 0;
                });
                $(this).keypress(function (e) {
                    idleTime = 0;
                });
            });
            $(document).on({
            "contextmenu": function(e) {
                console.log("ctx menu button:", e.which);//writing to console
                // Stop the context menu
                e.preventDefault();
             }});
    });
</script>
}
 